### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by jaklan** [mnazarov/ikeaprices#2]
Hello, 

The script doesn't seem to work anymore - clicking the bookmark has simply no effect, even on the provided demo product.

Regards.

**Comment by jaklan** [comment]
Okay, I have a solution - it's enough to replace:
```js
var priceElClass = "pip-price-module-price-module__price";
```
with:
```js
var priceElClass = "pip-temp-price-module__price";
```

**Comment by jaklan** [comment]
And one more improvement - I modified:
```js
var price = doc.evaluate("//div[@class='"+priceElClass+"']", doc, null, 4, null).iterateNext();
var text = cnt.substr(0, 2) + ': ' + (price === null ? "-" : price.textContent);
```

into

```js
var price = doc.evaluate("//div[@class='"+priceElClass+"']", doc, null, 4, null).iterateNext();
var priceCurrency = price.querySelector(".pip-temp-price__currency").textContent;
var priceInteger = price.querySelector(".pip-temp-price__integer").textContent;
var text = cnt.substr(0, 2) + ': ' + (price === null ? "-" : priceInteger + " " + priceCurrency);
 ```

so instead of:
<img width="422" alt="image" src="https://user-images.githubusercontent.com/24907857/201347241-b83dd787-ddcb-4ed9-88ff-419f2fdc37e6.png">

we get:
<img width="422" alt="image" src="https://user-images.githubusercontent.com/24907857/201347294-dbcc2c6a-47b6-4b04-b37b-e2cfabd8a5af.png">

**Comment by mnazarov** [comment]
Thanks for notifying, and sorry for a delay. I have now fixed the code. I used a slightly different way to remove the duplication in the prices
