### ISSUE TITLE
Currency conversion

### ISSUE THREAD

**Issue by Remy-Del9127** [mnazarov/ikeaprices#5]
I love this script but I still have to manually do conversion for countries that are not using euros. What would be awesome would be to have the option to display a converted price in a selected currency! 

Example:
Price on website used 
Country code | price local currency | price converted in selected currency

**Comment by mnazarov** [comment]
Hi, thanks, but I don't think it is easy to do - unless ikea provides the converted prices - which I couldn't find anywhere...
Since we are working in JS on the client side, and can only make requests to other ikea.com sub-pages, we don't really have a way to get currency exchange rates

**Comment by mnazarov** [comment]
As I wrote above I don't think it is currently possible
