### ISSUE TITLE
Price comparisons on favourites

### ISSUE THREAD

**Issue by grappler** [mnazarov/ikeaprices#6]
Hi

Great tool. Will test it out more.

Would be interesting to be able to run on the favourites/shopping list so to compare multiple products at the same time.

**Comment by mnazarov** [comment]
Hi @grappler,
Thanks for the suggestion, sounds like a good idea, and after having a quick look it seems feasible. I will see what I can do.

**Comment by mnazarov** [comment]
hi @grappler, the functionality is now implemented, remember to re-create your bookmarklet button

**Comment by grappler** [comment]
Thanks! Works great!
